const odooLocation = {
  AF: {code: 'base.af', name: 'Afghanistan', id: 3},
  AL: {code: 'base.al', name: 'Albania', id: 6},
  DZ: {code: 'base.dz', name: 'Algeria', id: 62},
  AS: {code: 'base.as', name: 'American Samoa', id: 11},
  AD: {code: 'base.ad', name: 'Andorra', id: 1},
  AO: {code: 'base.ao', name: 'Angola', id: 8},
  AI: {code: 'base.ai', name: 'Anguilla', id: 5},
  AQ: {code: 'base.aq', name: 'Antarctica', id: 9},
  AG: {code: 'base.ag', name: 'Antigua and Barbuda', id: 4},
  AR: {
    code: 'base.ar',
    states: {
      A: {code: 'base.state_ar_a', name: 'Salta', id: 569},
      B: {code: 'base.state_ar_b', name: 'Buenos Aires', id: 554},
      C: {
        code: 'base.state_ar_c',
        name: 'Ciudad Autónoma de Buenos Aires',
        id: 553,
      },
      D: {code: 'base.state_ar_d', name: 'San Luis', id: 571},
      E: {code: 'base.state_ar_e', name: 'Entre Ríos', id: 560},
      F: {code: 'base.state_ar_f', name: 'La Rioja', id: 564},
      G: {
        code: 'base.state_ar_g',
        name: 'Santiago Del Estero',
        id: 574,
      },
      H: {code: 'base.state_ar_h', name: 'Chaco', id: 556},
      J: {code: 'base.state_ar_j', name: 'San Juan', id: 570},
      K: {code: 'base.state_ar_k', name: 'Catamarca', id: 555},
      L: {code: 'base.state_ar_l', name: 'La Pampa', id: 563},
      M: {code: 'base.state_ar_m', name: 'Mendoza', id: 565},
      N: {code: 'base.state_ar_n', name: 'Misiones', id: 566},
      P: {code: 'base.state_ar_p', name: 'Formosa', id: 561},
      Q: {code: 'base.state_ar_q', name: 'Neuquén', id: 567},
      R: {code: 'base.state_ar_r', name: 'Río Negro', id: 568},
      S: {code: 'base.state_ar_s', name: 'Santa Fe', id: 573},
      T: {code: 'base.state_ar_t', name: 'Tucumán', id: 576},
      U: {code: 'base.state_ar_u', name: 'Chobut', id: 557},
      V: {code: 'base.state_ar_v', name: 'Tierra del Fuego', id: 575},
      W: {code: 'base.state_ar_w', name: 'Corrientes', id: 559},
      X: {code: 'base.state_ar_x', name: 'Córdoba', id: 558},
      Y: {code: 'base.state_ar_y', name: 'Jujuy', id: 562},
      Z: {code: 'base.state_ar_z', name: 'Santa Cruz', id: 572},
    },
    name: 'Argentina',
    id: 10,
  },
  AM: {code: 'base.am', name: 'Armenia', id: 7},
  AW: {code: 'base.aw', name: 'Aruba', id: 14},
  AU: {
    code: 'base.au',
    states: {
      ACT: {
        code: 'base.state_au_1',
        name: 'Australian Capital Territory',
        id: 1,
      },
      NSW: {code: 'base.state_au_2', name: 'New South Wales', id: 2},
      NT: {code: 'base.state_au_3', name: 'Northern Territory', id: 3},
      QLD: {code: 'base.state_au_4', name: 'Queensland', id: 4},
      SA: {code: 'base.state_au_5', name: 'South Australia', id: 5},
      TAS: {code: 'base.state_au_6', name: 'Tasmania', id: 6},
      VIC: {code: 'base.state_au_7', name: 'Victoria', id: 7},
      WA: {code: 'base.state_au_8', name: 'Western Australia', id: 8},
    },
    name: 'Australia',
    id: 13,
  },
  AT: {code: 'base.at', name: 'Austria', id: 12},
  AZ: {code: 'base.az', name: 'Azerbaijan', id: 16},
  BS: {code: 'base.bs', name: 'Bahamas', id: 32},
  BH: {code: 'base.bh', name: 'Bahrain', id: 23},
  BD: {code: 'base.bd', name: 'Bangladesh', id: 19},
  BB: {code: 'base.bb', name: 'Barbados', id: 18},
  BY: {code: 'base.by', name: 'Belarus', id: 36},
  BE: {code: 'base.be', name: 'Belgium', id: 20},
  BZ: {code: 'base.bz', name: 'Belize', id: 37},
  BJ: {code: 'base.bj', name: 'Benin', id: 25},
  BM: {code: 'base.bm', name: 'Bermuda', id: 27},
  BT: {code: 'base.bt', name: 'Bhutan', id: 33},
  BO: {code: 'base.bo', name: 'Bolivia', id: 29},
  BQ: {
    code: 'base.bq',
    name: 'Bonaire, Sint Eustatius and Saba',
    id: 30,
  },
  BA: {code: 'base.ba', name: 'Bosnia and Herzegovina', id: 17},
  BW: {code: 'base.bw', name: 'Botswana', id: 35},
  BV: {code: 'base.bv', name: 'Bouvet Island', id: 34},
  BR: {
    code: 'base.br',
    states: {
      AC: {code: 'base.state_br_ac', name: 'Acre', id: 71},
      AL: {code: 'base.state_br_al', name: 'Alagoas', id: 72},
      AM: {code: 'base.state_br_am', name: 'Amazonas', id: 74},
      AP: {code: 'base.state_br_ap', name: 'Amapá', id: 73},
      BA: {code: 'base.state_br_ba', name: 'Bahia', id: 75},
      CE: {code: 'base.state_br_ce', name: 'Ceará', id: 76},
      DF: {code: 'base.state_br_df', name: 'Distrito Federal', id: 77},
      ES: {code: 'base.state_br_es', name: 'Espírito Santo', id: 78},
      GO: {code: 'base.state_br_go', name: 'Goiás', id: 79},
      MA: {code: 'base.state_br_ma', name: 'Maranhão', id: 80},
      MG: {code: 'base.state_br_mg', name: 'Minas Gerais', id: 83},
      MS: {
        code: 'base.state_br_ms',
        name: 'Mato Grosso do Sul',
        id: 82,
      },
      MT: {code: 'base.state_br_mt', name: 'Mato Grosso', id: 81},
      PA: {code: 'base.state_br_pa', name: 'Pará', id: 84},
      PB: {code: 'base.state_br_pb', name: 'Paraíba', id: 85},
      PE: {code: 'base.state_br_pe', name: 'Pernambuco', id: 87},
      PI: {code: 'base.state_br_pi', name: 'Piauí', id: 88},
      PR: {code: 'base.state_br_pr', name: 'Paraná', id: 86},
      RJ: {code: 'base.state_br_rj', name: 'Rio de Janeiro', id: 89},
      RN: {
        code: 'base.state_br_rn',
        name: 'Rio Grande do Norte',
        id: 90,
      },
      RO: {code: 'base.state_br_ro', name: 'Rondônia', id: 92},
      RR: {code: 'base.state_br_rr', name: 'Roraima', id: 93},
      RS: {
        code: 'base.state_br_rs',
        name: 'Rio Grande do Sul',
        id: 91,
      },
      SC: {code: 'base.state_br_sc', name: 'Santa Catarina', id: 94},
      SE: {code: 'base.state_br_se', name: 'Sergipe', id: 96},
      SP: {code: 'base.state_br_sp', name: 'São Paulo', id: 95},
      TO: {code: 'base.state_br_to', name: 'Tocantins', id: 97},
    },
    name: 'Brazil',
    id: 31,
  },
  IO: {
    code: 'base.io',
    name: 'British Indian Ocean Territory',
    id: 105,
  },
  BN: {code: 'base.bn', name: 'Brunei Darussalam', id: 28},
  BG: {code: 'base.bg', name: 'Bulgaria', id: 22},
  BF: {code: 'base.bf', name: 'Burkina Faso', id: 21},
  BI: {code: 'base.bi', name: 'Burundi', id: 24},
  KH: {code: 'base.kh', name: 'Cambodia', id: 116},
  CM: {code: 'base.cm', name: 'Cameroon', id: 47},
  CA: {
    code: 'base.ca',
    states: {
      AB: {code: 'base.state_ca_ab', name: 'Alberta', id: 533},
      BC: {
        code: 'base.state_ca_bc',
        name: 'British Columbia',
        id: 534,
      },
      MB: {code: 'base.state_ca_mb', name: 'Manitoba', id: 535},
      NB: {code: 'base.state_ca_nb', name: 'New Brunswick', id: 536},
      NL: {
        code: 'base.state_ca_nl',
        name: 'Newfoundland and Labrador',
        id: 537,
      },
      NS: {code: 'base.state_ca_ns', name: 'Nova Scotia', id: 539},
      NT: {
        code: 'base.state_ca_nt',
        name: 'Northwest Territories',
        id: 538,
      },
      NU: {code: 'base.state_ca_nu', name: 'Nunavut', id: 540},
      ON: {code: 'base.state_ca_on', name: 'Ontario', id: 541},
      PE: {
        code: 'base.state_ca_pe',
        name: 'Prince Edward Island',
        id: 542,
      },
      QC: {code: 'base.state_ca_qc', name: 'Quebec', id: 543},
      SK: {code: 'base.state_ca_sk', name: 'Saskatchewan', id: 544},
      YT: {code: 'base.state_ca_yt', name: 'Yukon', id: 545},
    },
    name: 'Canada',
    id: 38,
  },
  CV: {code: 'base.cv', name: 'Cape Verde', id: 52},
  KY: {code: 'base.ky', name: 'Cayman Islands', id: 123},
  CF: {code: 'base.cf', name: 'Central African Republic', id: 40},
  TD: {code: 'base.td', name: 'Chad', id: 214},
  CL: {code: 'base.cl', name: 'Chile', id: 46},
  CN: {code: 'base.cn', name: 'China', id: 48},
  CX: {code: 'base.cx', name: 'Christmas Island', id: 54},
  CC: {code: 'base.cc', name: 'Cocos (Keeling) Islands', id: 39},
  CO: {
    code: 'base.co',
    states: {
      AMA: {code: 'base.state_co_29', name: 'Amazonas', id: 675},
      ANT: {code: 'base.state_co_01', name: 'Antioquia', id: 647},
      ARA: {code: 'base.state_co_25', name: 'Arauca', id: 671},
      ATL: {code: 'base.state_co_02', name: 'Atlántico', id: 648},
      BOL: {code: 'base.state_co_04', name: 'Bolívar', id: 650},
      BOY: {code: 'base.state_co_05', name: 'Boyacá', id: 651},
      CAL: {code: 'base.state_co_06', name: 'Caldas', id: 652},
      CAQ: {code: 'base.state_co_07', name: 'Caquetá', id: 653},
      CAS: {code: 'base.state_co_26', name: 'Casanare', id: 672},
      CAU: {code: 'base.state_co_08', name: 'Cauca', id: 654},
      CES: {code: 'base.state_co_09', name: 'Cesar', id: 655},
      CHO: {code: 'base.state_co_12', name: 'Chocó', id: 658},
      COR: {code: 'base.state_co_10', name: 'Córdoba', id: 656},
      CUN: {code: 'base.state_co_11', name: 'Cundinamarca', id: 657},
      DC: {code: 'base.state_co_03', name: 'D.C.', id: 649},
      GUA: {code: 'base.state_co_30', name: 'Guainía', id: 676},
      GUV: {code: 'base.state_co_31', name: 'Guaviare', id: 677},
      HUI: {code: 'base.state_co_13', name: 'Huila', id: 659},
      LAG: {code: 'base.state_co_14', name: 'La Guajira', id: 660},
      MAG: {code: 'base.state_co_15', name: 'Magdalena', id: 661},
      MET: {code: 'base.state_co_16', name: 'Meta', id: 662},
      NAR: {code: 'base.state_co_17', name: 'Nariño', id: 663},
      NSA: {
        code: 'base.state_co_18',
        name: 'Norte de Santander',
        id: 664,
      },
      PUT: {code: 'base.state_co_27', name: 'Putumayo', id: 673},
      QUI: {code: 'base.state_co_19', name: 'Quindio', id: 665},
      RIS: {code: 'base.state_co_20', name: 'Risaralda', id: 666},
      SAN: {code: 'base.state_co_21', name: 'Santander', id: 667},
      SAP: {
        code: 'base.state_co_28',
        name: 'Archipiélago de San Andrés, Providencia y Santa Catalina',
        id: 674,
      },
      SUC: {code: 'base.state_co_22', name: 'Sucre', id: 668},
      TOL: {code: 'base.state_co_23', name: 'Tolima', id: 669},
      VAC: {
        code: 'base.state_co_24',
        name: 'Valle del Cauca',
        id: 670,
      },
      VAU: {code: 'base.state_co_32', name: 'Vaupés', id: 678},
      VID: {code: 'base.state_co_33', name: 'Vichada', id: 679},
    },
    name: 'Colombia',
    id: 49,
  },
  KM: {code: 'base.km', name: 'Comoros', id: 118},
  CG: {code: 'base.cg', name: 'Congo', id: 42},
  CK: {code: 'base.ck', name: 'Cook Islands', id: 45},
  CR: {code: 'base.cr', name: 'Costa Rica', id: 50},
  HR: {code: 'base.hr', name: 'Croatia', id: 97},
  CU: {code: 'base.cu', name: 'Cuba', id: 51},
  CW: {code: 'base.cw', name: 'Curaçao', id: 53},
  CY: {code: 'base.cy', name: 'Cyprus', id: 55},
  CZ: {code: 'base.cz', name: 'Czech Republic', id: 56},
  CI: {code: 'base.ci', name: "Côte d'Ivoire", id: 44},
  CD: {
    code: 'base.cd',
    name: 'Democratic Republic of the Congo',
    id: 41,
  },
  DK: {code: 'base.dk', name: 'Denmark', id: 59},
  DJ: {code: 'base.dj', name: 'Djibouti', id: 58},
  DM: {code: 'base.dm', name: 'Dominica', id: 60},
  DO: {code: 'base.do', name: 'Dominican Republic', id: 61},
  EC: {code: 'base.ec', name: 'Ecuador', id: 63},
  EG: {
    code: 'base.eg',
    states: {
      ALX: {code: 'base.state_eg_alx', name: 'Alexandria', id: 273},
      ASN: {code: 'base.state_eg_asn', name: 'Aswan', id: 285},
      AST: {code: 'base.state_eg_ast', name: 'Asyut', id: 286},
      BA: {code: 'base.state_eg_ba', name: 'Red Sea', id: 269},
      BH: {code: 'base.state_eg_bh', name: 'Beheira', id: 270},
      BNS: {code: 'base.state_eg_bns', name: 'Beni Suef', id: 287},
      C: {code: 'base.state_eg_c', name: 'Cairo', id: 278},
      DK: {code: 'base.state_eg_dk', name: 'Dakahlia', id: 268},
      DT: {code: 'base.state_eg_dt', name: 'Damietta', id: 289},
      FYM: {code: 'base.state_eg_fym', name: 'Faiyum', id: 271},
      GH: {code: 'base.state_eg_gh', name: 'Gharbia', id: 272},
      GZ: {code: 'base.state_eg_gz', name: 'Giza', id: 275},
      HU: {code: 'base.state_eg_hu', name: 'Helwan', id: 290},
      IS: {code: 'base.state_eg_is', name: 'Ismailia', id: 274},
      JS: {code: 'base.state_eg_js', name: 'South Sinai', id: 291},
      KB: {code: 'base.state_eg_kb', name: 'Qalyubia', id: 279},
      KFS: {
        code: 'base.state_eg_kfs',
        name: 'Kafr el-Sheikh',
        id: 292,
      },
      KN: {code: 'base.state_eg_kn', name: 'Qena', id: 294},
      LX: {code: 'base.state_eg_lx', name: 'Luxor', id: 280},
      MN: {code: 'base.state_eg_mn', name: 'Minya', id: 277},
      MNF: {code: 'base.state_eg_mnf', name: 'Monufia', id: 276},
      MT: {code: 'base.state_eg_mt', name: 'Matrouh', id: 293},
      PTS: {code: 'base.state_eg_pts', name: 'Port Said', id: 288},
      SHG: {code: 'base.state_eg_shg', name: 'Sohag', id: 296},
      SHR: {code: 'base.state_eg_shr', name: 'Al Sharqia', id: 282},
      SIN: {code: 'base.state_eg_sin', name: 'North Sinai', id: 295},
      SU: {code: 'base.state_eg_su', name: '6th of October', id: 283},
      SUZ: {code: 'base.state_eg_suz', name: 'Suez', id: 284},
      WAD: {code: 'base.state_eg_wad', name: 'New Valley', id: 281},
    },
    name: 'Egypt',
    id: 65,
  },
  SV: {code: 'base.sv', name: 'El Salvador', id: 209},
  GQ: {code: 'base.gq', name: 'Equatorial Guinea', id: 87},
  ER: {code: 'base.er', name: 'Eritrea', id: 67},
  EE: {code: 'base.ee', name: 'Estonia', id: 64},
  ET: {code: 'base.et', name: 'Ethiopia', id: 69},
  FK: {code: 'base.fk', name: 'Falkland Islands', id: 72},
  FO: {code: 'base.fo', name: 'Faroe Islands', id: 74},
  FJ: {code: 'base.fj', name: 'Fiji', id: 71},
  FI: {code: 'base.fi', name: 'Finland', id: 70},
  FR: {code: 'base.fr', name: 'France', id: 75},
  GF: {code: 'base.gf', name: 'French Guiana', id: 79},
  PF: {code: 'base.pf', name: 'French Polynesia', id: 174},
  TF: {code: 'base.tf', name: 'French Southern Territories', id: 215},
  GA: {code: 'base.ga', name: 'Gabon', id: 76},
  GM: {code: 'base.gm', name: 'Gambia', id: 84},
  GE: {code: 'base.ge', name: 'Georgia', id: 78},
  DE: {code: 'base.de', name: 'Germany', id: 57},
  GH: {code: 'base.gh', name: 'Ghana', id: 80},
  GI: {code: 'base.gi', name: 'Gibraltar', id: 81},
  GR: {code: 'base.gr', name: 'Greece', id: 88},
  GL: {code: 'base.gl', name: 'Greenland', id: 83},
  GD: {code: 'base.gd', name: 'Grenada', id: 77},
  GP: {code: 'base.gp', name: 'Guadeloupe', id: 86},
  GU: {code: 'base.gu', name: 'Guam', id: 91},
  GT: {
    code: 'base.gt',
    states: {
      AVE: {code: 'base.state_gt_ave', name: 'Alta Verapaz', id: 179},
      BVE: {code: 'base.state_gt_bve', name: 'Baja Verapaz', id: 180},
      CMT: {code: 'base.state_gt_cmt', name: 'Chimaltenango', id: 181},
      CQM: {code: 'base.state_gt_cqm', name: 'Chiquimula', id: 182},
      EPR: {code: 'base.state_gt_epr', name: 'El Progreso', id: 183},
      ESC: {code: 'base.state_gt_esc', name: 'Escuintla', id: 184},
      GUA: {code: 'base.state_gt_gua', name: 'Guatemala', id: 185},
      HUE: {code: 'base.state_gt_hue', name: 'Huehuetenango', id: 186},
      IZA: {code: 'base.state_gt_iza', name: 'Izabal', id: 187},
      JAL: {code: 'base.state_gt_jal', name: 'Jalapa', id: 188},
      JUT: {code: 'base.state_gt_jut', name: 'Jutiapa', id: 189},
      PET: {code: 'base.state_gt_pet', name: 'Petén', id: 190},
      QUE: {
        code: 'base.state_gt_que',
        name: 'Quetzaltenango',
        id: 191,
      },
      QUI: {code: 'base.state_gt_qui', name: 'Quiché', id: 192},
      RET: {code: 'base.state_gt_ret', name: 'Retalhuleu', id: 193},
      SAC: {code: 'base.state_gt_sac', name: 'Sacatepéquez', id: 194},
      SMA: {code: 'base.state_gt_sma', name: 'San Marcos', id: 195},
      SOL: {code: 'base.state_gt_sol', name: 'Sololá', id: 197},
      SRO: {code: 'base.state_gt_sro', name: 'Santa Rosa', id: 196},
      SUC: {code: 'base.state_gt_suc', name: 'Suchitepéquez', id: 198},
      TOT: {code: 'base.state_gt_tot', name: 'Totonicapán', id: 199},
      ZAC: {code: 'base.state_gt_zac', name: 'Zacapa', id: 200},
    },
    name: 'Guatemala',
    id: 90,
  },
  GG: {code: 'base.gg', name: 'Guernsey', id: 82},
  GN: {code: 'base.gn', name: 'Guinea', id: 85},
  GW: {code: 'base.gw', name: 'Guinea-Bissau', id: 92},
  GY: {code: 'base.gy', name: 'Guyana', id: 93},
  HT: {code: 'base.ht', name: 'Haiti', id: 98},
  HM: {
    code: 'base.hm',
    name: 'Heard Island and McDonald Islands',
    id: 95,
  },
  VA: {
    code: 'base.va',
    name: 'Holy See (Vatican City State)',
    id: 236,
  },
  HN: {code: 'base.hn', name: 'Honduras', id: 96},
  HK: {code: 'base.hk', name: 'Hong Kong', id: 94},
  HU: {code: 'base.hu', name: 'Hungary', id: 99},
  IS: {code: 'base.is', name: 'Iceland', id: 108},
  IN: {
    code: 'base.in',
    states: {
      AN: {
        code: 'base.state_in_an',
        name: 'Andaman and Nicobar',
        id: 577,
      },
      AP: {code: 'base.state_in_ap', name: 'Andhra Pradesh', id: 578},
      AR: {
        code: 'base.state_in_ar',
        name: 'Arunachal Pradesh',
        id: 579,
      },
      AS: {code: 'base.state_in_as', name: 'Assam', id: 580},
      BR: {code: 'base.state_in_br', name: 'Bihar', id: 581},
      CG: {code: 'base.state_in_cg', name: 'Chattisgarh', id: 583},
      CH: {code: 'base.state_in_ch', name: 'Chandigarh', id: 582},
      DD: {code: 'base.state_in_dd', name: 'Daman and Diu', id: 585},
      DL: {code: 'base.state_in_dl', name: 'Delhi', id: 586},
      DN: {
        code: 'base.state_in_dn',
        name: 'Dadra and Nagar Haveli',
        id: 584,
      },
      GA: {code: 'base.state_in_ga', name: 'Goa', id: 587},
      GJ: {code: 'base.state_in_gj', name: 'Gujarat', id: 588},
      HP: {
        code: 'base.state_in_hp',
        name: 'Himachal Pradesh',
        id: 590,
      },
      HR: {code: 'base.state_in_hr', name: 'Haryana', id: 589},
      JH: {code: 'base.state_in_jh', name: 'Jharkhand', id: 592},
      JK: {
        code: 'base.state_in_jk',
        name: 'Jammu and Kashmir',
        id: 591,
      },
      KA: {code: 'base.state_in_ka', name: 'Karnataka', id: 593},
      KL: {code: 'base.state_in_kl', name: 'Kerala', id: 594},
      LD: {code: 'base.state_in_ld', name: 'Lakshadweep', id: 595},
      MH: {code: 'base.state_in_mh', name: 'Maharashtra', id: 597},
      ML: {code: 'base.state_in_ml', name: 'Meghalaya', id: 599},
      MN: {code: 'base.state_in_mn', name: 'Manipur', id: 598},
      MP: {code: 'base.state_in_mp', name: 'Madhya Pradesh', id: 596},
      MZ: {code: 'base.state_in_mz', name: 'Mizoram', id: 600},
      NL: {code: 'base.state_in_nl', name: 'Nagaland', id: 601},
      OR: {code: 'base.state_in_or', name: 'Orissa', id: 602},
      PB: {code: 'base.state_in_pb', name: 'Punjab', id: 604},
      PY: {code: 'base.state_in_py', name: 'Puducherry', id: 603},
      RJ: {code: 'base.state_in_rj', name: 'Rajasthan', id: 605},
      SK: {code: 'base.state_in_sk', name: 'Sikkim', id: 606},
      TN: {code: 'base.state_in_tn', name: 'Tamil Nadu', id: 607},
      TR: {code: 'base.state_in_tr', name: 'Tripura', id: 609},
      TS: {code: 'base.state_in_ts', name: 'Telangana', id: 608},
      UK: {code: 'base.state_in_uk', name: 'Uttarakhand', id: 611},
      UP: {code: 'base.state_in_up', name: 'Uttar Pradesh', id: 610},
      WB: {code: 'base.state_in_wb', name: 'West Bengal', id: 612},
    },
    name: 'India',
    id: 104,
  },
  ID: {
    code: 'base.id',
    states: {
      AC: {code: 'base.state_id_ac', name: 'Aceh', id: 613},
      BA: {code: 'base.state_id_ba', name: 'Bali', id: 614},
      BB: {code: 'base.state_id_bb', name: 'Bangka Belitung', id: 615},
      BE: {code: 'base.state_id_be', name: 'Bengkulu', id: 617},
      BT: {code: 'base.state_id_bt', name: 'Banten', id: 616},
      GO: {code: 'base.state_id_go', name: 'Gorontalo', id: 618},
      JA: {code: 'base.state_id_ja', name: 'Jambi', id: 620},
      JB: {code: 'base.state_id_jb', name: 'Jawa Barat', id: 621},
      JI: {code: 'base.state_id_ji', name: 'Jawa Timur', id: 623},
      JK: {code: 'base.state_id_jk', name: 'Jakarta', id: 619},
      JT: {code: 'base.state_id_jt', name: 'Jawa Tengah', id: 622},
      KB: {
        code: 'base.state_id_kb',
        name: 'Kalimantan Barat',
        id: 624,
      },
      KI: {
        code: 'base.state_id_ki',
        name: 'Kalimantan Timur',
        id: 627,
      },
      KR: {code: 'base.state_id_kr', name: 'Kepulauan Riau', id: 629},
      KS: {
        code: 'base.state_id_ks',
        name: 'Kalimantan Selatan',
        id: 625,
      },
      KT: {
        code: 'base.state_id_kt',
        name: 'Kalimantan Tengah',
        id: 626,
      },
      KU: {
        code: 'base.state_id_ku',
        name: 'Kalimantan Utara',
        id: 628,
      },
      LA: {code: 'base.state_id_la', name: 'Lampung', id: 630},
      MA: {code: 'base.state_id_ma', name: 'Maluku', id: 631},
      MU: {code: 'base.state_id_mu', name: 'Maluku Utara', id: 632},
      NB: {
        code: 'base.state_id_nb',
        name: 'Nusa Tenggara Barat',
        id: 633,
      },
      NT: {
        code: 'base.state_id_nt',
        name: 'Nusa Tenggara Timur',
        id: 634,
      },
      PA: {code: 'base.state_id_pa', name: 'Papua', id: 635},
      PB: {code: 'base.state_id_pb', name: 'Papua Barat', id: 636},
      RI: {code: 'base.state_id_ri', name: 'Riau', id: 637},
      SA: {code: 'base.state_id_sa', name: 'Sulawesi Utara', id: 642},
      SB: {code: 'base.state_id_sb', name: 'Sumatra Barat', id: 643},
      SG: {
        code: 'base.state_id_sg',
        name: 'Sulawesi Tenggara',
        id: 641,
      },
      SN: {
        code: 'base.state_id_sn',
        name: 'Sulawesi Selatan',
        id: 639,
      },
      SR: {code: 'base.state_id_sr', name: 'Sulawesi Barat', id: 638},
      SS: {code: 'base.state_id_ss', name: 'Sumatra Selatan', id: 644},
      ST: {code: 'base.state_id_st', name: 'Sulawesi Tengah', id: 640},
      SU: {code: 'base.state_id_su', name: 'Sumatra Utara', id: 645},
      YO: {code: 'base.state_id_yo', name: 'Yogyakarta', id: 646},
    },
    name: 'Indonesia',
    id: 100,
  },
  IR: {code: 'base.ir', name: 'Iran', id: 107},
  IQ: {code: 'base.iq', name: 'Iraq', id: 106},
  IE: {code: 'base.ie', name: 'Ireland', id: 101},
  IM: {code: 'base.im', name: 'Isle of Man', id: 103},
  IL: {code: 'base.il', name: 'Israel', id: 102},
  IT: {
    code: 'base.it',
    states: {
      AG: {code: 'base.state_it_ag', name: 'Agrigento', id: 306},
      AL: {code: 'base.state_it_al', name: 'Alessandria', id: 307},
      AN: {code: 'base.state_it_an', name: 'Ancona', id: 308},
      AO: {code: 'base.state_it_ao', name: 'Aosta', id: 309},
      AP: {code: 'base.state_it_ap', name: 'Ascoli Piceno', id: 311},
      AQ: {code: 'base.state_it_aq', name: "L'Aquila", id: 350},
      AR: {code: 'base.state_it_ar', name: 'Arezzo', id: 310},
      AT: {code: 'base.state_it_at', name: 'Asti', id: 312},
      AV: {code: 'base.state_it_av', name: 'Avellino', id: 313},
      BA: {code: 'base.state_it_ba', name: 'Bari', id: 314},
      BG: {code: 'base.state_it_bg', name: 'Bergamo', id: 318},
      BI: {code: 'base.state_it_bi', name: 'Biella', id: 319},
      BL: {code: 'base.state_it_bl', name: 'Belluno', id: 316},
      BN: {code: 'base.state_it_bn', name: 'Benevento', id: 317},
      BO: {code: 'base.state_it_bo', name: 'Bologna', id: 320},
      BR: {code: 'base.state_it_br', name: 'Brindisi', id: 323},
      BS: {code: 'base.state_it_bs', name: 'Brescia', id: 322},
      BT: {
        code: 'base.state_it_bt',
        name: 'Barletta-Andria-Trani',
        id: 315,
      },
      BZ: {code: 'base.state_it_bz', name: 'Bolzano', id: 321},
      CA: {code: 'base.state_it_ca', name: 'Cagliari', id: 324},
      CB: {code: 'base.state_it_cb', name: 'Campobasso', id: 326},
      CE: {code: 'base.state_it_ce', name: 'Caserta', id: 328},
      CH: {code: 'base.state_it_ch', name: 'Chieti', id: 331},
      CI: {
        code: 'base.state_it_ci',
        name: 'Carbonia-Iglesias',
        id: 327,
      },
      CL: {code: 'base.state_it_cl', name: 'Caltanissetta', id: 325},
      CN: {code: 'base.state_it_cn', name: 'Cuneo', id: 336},
      CO: {code: 'base.state_it_co', name: 'Como', id: 332},
      CR: {code: 'base.state_it_cr', name: 'Cremona', id: 334},
      CS: {code: 'base.state_it_cs', name: 'Cosenza', id: 333},
      CT: {code: 'base.state_it_ct', name: 'Catania', id: 329},
      CZ: {code: 'base.state_it_cz', name: 'Catanzaro', id: 330},
      EN: {code: 'base.state_it_en', name: 'Enna', id: 337},
      FC: {code: 'base.state_it_fc', name: 'Forlì-Cesena', id: 342},
      FE: {code: 'base.state_it_fe', name: 'Ferrara', id: 339},
      FG: {code: 'base.state_it_fg', name: 'Foggia', id: 341},
      FI: {code: 'base.state_it_fi', name: 'Firenze', id: 340},
      FM: {code: 'base.state_it_fm', name: 'Fermo', id: 338},
      FR: {code: 'base.state_it_fr', name: 'Frosinone', id: 343},
      GE: {code: 'base.state_it_ge', name: 'Genova', id: 344},
      GO: {code: 'base.state_it_go', name: 'Gorizia', id: 345},
      GR: {code: 'base.state_it_gr', name: 'Grosseto', id: 346},
      IM: {code: 'base.state_it_im', name: 'Imperia', id: 347},
      IS: {code: 'base.state_it_is', name: 'Isernia', id: 348},
      KR: {code: 'base.state_it_kr', name: 'Crotone', id: 335},
      LC: {code: 'base.state_it_lc', name: 'Lecco', id: 353},
      LE: {code: 'base.state_it_le', name: 'Lecce', id: 352},
      LI: {code: 'base.state_it_li', name: 'Livorno', id: 354},
      LO: {code: 'base.state_it_lo', name: 'Lodi', id: 355},
      LT: {code: 'base.state_it_lt', name: 'Latina', id: 351},
      LU: {code: 'base.state_it_lu', name: 'Lucca', id: 356},
      MB: {code: 'base.state_it_mb', name: 'Monza e Brianza', id: 365},
      MC: {code: 'base.state_it_mc', name: 'Macerata', id: 357},
      ME: {code: 'base.state_it_me', name: 'Messina', id: 362},
      MI: {code: 'base.state_it_mi', name: 'Milano', id: 363},
      MN: {code: 'base.state_it_mn', name: 'Mantova', id: 358},
      MO: {code: 'base.state_it_mo', name: 'Modena', id: 364},
      MS: {code: 'base.state_it_ms', name: 'Massa-Carrara', id: 359},
      MT: {code: 'base.state_it_mt', name: 'Matera', id: 360},
      NA: {code: 'base.state_it_na', name: 'Napoli', id: 366},
      NO: {code: 'base.state_it_no', name: 'Novara', id: 367},
      NU: {code: 'base.state_it_nu', name: 'Nuoro', id: 368},
      OG: {code: 'base.state_it_og', name: 'Ogliastra', id: 369},
      OR: {code: 'base.state_it_or', name: 'Oristano', id: 371},
      OT: {code: 'base.state_it_ot', name: 'Olbia-Tempio', id: 370},
      PA: {code: 'base.state_it_pa', name: 'Palermo', id: 373},
      PC: {code: 'base.state_it_pc', name: 'Piacenza', id: 379},
      PD: {code: 'base.state_it_pd', name: 'Padova', id: 372},
      PE: {code: 'base.state_it_pe', name: 'Pescara', id: 378},
      PG: {code: 'base.state_it_pg', name: 'Perugia', id: 376},
      PI: {code: 'base.state_it_pi', name: 'Pisa', id: 380},
      PN: {code: 'base.state_it_pn', name: 'Pordenone', id: 382},
      PO: {code: 'base.state_it_po', name: 'Prato', id: 384},
      PR: {code: 'base.state_it_pr', name: 'Parma', id: 374},
      PT: {code: 'base.state_it_pt', name: 'Pistoia', id: 381},
      PU: {code: 'base.state_it_pu', name: 'Pesaro e Urbino', id: 377},
      PV: {code: 'base.state_it_pv', name: 'Pavia', id: 375},
      PZ: {code: 'base.state_it_pz', name: 'Potenza', id: 383},
      RA: {code: 'base.state_it_ra', name: 'Ravenna', id: 386},
      RC: {code: 'base.state_it_rc', name: 'Reggio Calabria', id: 387},
      RE: {code: 'base.state_it_re', name: 'Reggio Emilia', id: 388},
      RG: {code: 'base.state_it_rg', name: 'Ragusa', id: 385},
      RI: {code: 'base.state_it_ri', name: 'Rieti', id: 389},
      RM: {code: 'base.state_it_rm', name: 'Roma', id: 391},
      RN: {code: 'base.state_it_rn', name: 'Rimini', id: 390},
      RO: {code: 'base.state_it_ro', name: 'Rovigo', id: 392},
      SA: {code: 'base.state_it_sa', name: 'Salerno', id: 393},
      SI: {code: 'base.state_it_si', name: 'Siena', id: 396},
      SO: {code: 'base.state_it_so', name: 'Sondrio', id: 398},
      SP: {code: 'base.state_it_sp', name: 'La Spezia', id: 349},
      SR: {code: 'base.state_it_sr', name: 'Siracusa', id: 397},
      SS: {code: 'base.state_it_ss', name: 'Sassari', id: 394},
      SU: {code: 'base.state_it_su', name: 'Sud Sardegna', id: 399},
      SV: {code: 'base.state_it_sv', name: 'Savona', id: 395},
      TA: {code: 'base.state_it_ta', name: 'Taranto', id: 400},
      TE: {code: 'base.state_it_te', name: 'Teramo', id: 401},
      TN: {code: 'base.state_it_tn', name: 'Trento', id: 405},
      TO: {code: 'base.state_it_to', name: 'Torino', id: 403},
      TP: {code: 'base.state_it_tp', name: 'Trapani', id: 404},
      TR: {code: 'base.state_it_tr', name: 'Terni', id: 402},
      TS: {code: 'base.state_it_ts', name: 'Trieste', id: 407},
      TV: {code: 'base.state_it_tv', name: 'Treviso', id: 406},
      UD: {code: 'base.state_it_ud', name: 'Udine', id: 408},
      VA: {code: 'base.state_it_va', name: 'Varese', id: 409},
      VB: {
        code: 'base.state_it_vb',
        name: 'Verbano-Cusio-Ossola',
        id: 411,
      },
      VC: {code: 'base.state_it_vc', name: 'Vercelli', id: 412},
      VE: {code: 'base.state_it_ve', name: 'Venezia', id: 410},
      VI: {code: 'base.state_it_vi', name: 'Vicenza', id: 415},
      VR: {code: 'base.state_it_vr', name: 'Verona', id: 413},
      VS: {code: 'base.state_it_vs', name: 'Medio Campidano', id: 361},
      VT: {code: 'base.state_it_vt', name: 'Viterbo', id: 416},
      VV: {code: 'base.state_it_vv', name: 'Vibo Valentia', id: 414},
    },
    name: 'Italy',
    id: 109,
  },
  JM: {code: 'base.jm', name: 'Jamaica', id: 111},
  JP: {
    code: 'base.jp',
    states: {
      1: {code: 'base.state_jp_jp-01', name: 'Hokkaidō', id: 212},
      'JP-1': {code: 'base.state_jp_jp-01', name: 'Hokkaidō', id: 212},
      2: {code: 'base.state_jp_jp-02', name: 'Aomori', id: 203},
      'JP-2': {code: 'base.state_jp_jp-02', name: 'Aomori', id: 203},
      3: {code: 'base.state_jp_jp-03', name: 'Iwate', id: 216},
      'JP-3': {code: 'base.state_jp_jp-03', name: 'Iwate', id: 216},
      4: {code: 'base.state_jp_jp-04', name: 'Miyagi', id: 224},
      'JP-4': {code: 'base.state_jp_jp-04', name: 'Miyagi', id: 224},
      5: {code: 'base.state_jp_jp-05', name: 'Akita', id: 202},
      'JP-5': {code: 'base.state_jp_jp-05', name: 'Akita', id: 202},
      6: {code: 'base.state_jp_jp-06', name: 'Yamagata', id: 245},
      'JP-6': {code: 'base.state_jp_jp-06', name: 'Yamagata', id: 245},
      7: {code: 'base.state_jp_jp-07', name: 'Fukushima', id: 208},
      'JP-7': {code: 'base.state_jp_jp-07', name: 'Fukushima', id: 208},
      8: {code: 'base.state_jp_jp-08', name: 'Ibaraki', id: 214},
      'JP-8': {code: 'base.state_jp_jp-08', name: 'Ibaraki', id: 214},
      9: {code: 'base.state_jp_jp-09', name: 'Tochigi', id: 239},
      'JP-9': {code: 'base.state_jp_jp-09', name: 'Tochigi', id: 239},
      10: {code: 'base.state_jp_jp-10', name: 'Gunma', id: 210},
      'JP-10': {code: 'base.state_jp_jp-10', name: 'Gunma', id: 210},
      11: {code: 'base.state_jp_jp-11', name: 'Saitama', id: 235},
      'JP-11': {code: 'base.state_jp_jp-11', name: 'Saitama', id: 235},
      12: {code: 'base.state_jp_jp-12', name: 'Chiba', id: 204},
      'JP-12': {code: 'base.state_jp_jp-12', name: 'Chiba', id: 204},
      13: {code: 'base.state_jp_jp-13', name: 'Tōkyō', id: 243},
      'JP-13': {code: 'base.state_jp_jp-13', name: 'Tōkyō', id: 243},
      14: {code: 'base.state_jp_jp-14', name: 'Kanagawa', id: 219},
      'JP-14': {code: 'base.state_jp_jp-14', name: 'Kanagawa', id: 219},
      15: {code: 'base.state_jp_jp-15', name: 'Niigata', id: 229},
      'JP-15': {code: 'base.state_jp_jp-15', name: 'Niigata', id: 229},
      16: {code: 'base.state_jp_jp-16', name: 'Toyama', id: 242},
      'JP-16': {code: 'base.state_jp_jp-16', name: 'Toyama', id: 242},
      17: {code: 'base.state_jp_jp-17', name: 'Ishikawa', id: 215},
      'JP-17': {code: 'base.state_jp_jp-17', name: 'Ishikawa', id: 215},
      18: {code: 'base.state_jp_jp-18', name: 'Fukui', id: 206},
      'JP-18': {code: 'base.state_jp_jp-18', name: 'Fukui', id: 206},
      19: {code: 'base.state_jp_jp-19', name: 'Yamanashi', id: 247},
      'JP-19': {code: 'base.state_jp_jp-19', name: 'Yamanashi', id: 247},
      20: {code: 'base.state_jp_jp-20', name: 'Nagano', id: 226},
      'JP-20': {code: 'base.state_jp_jp-20', name: 'Nagano', id: 226},
      21: {code: 'base.state_jp_jp-21', name: 'Gifu', id: 209},
      'JP-21': {code: 'base.state_jp_jp-21', name: 'Gifu', id: 209},
      22: {code: 'base.state_jp_jp-22', name: 'Shizuoka', id: 238},
      'JP-22': {code: 'base.state_jp_jp-22', name: 'Shizuoka', id: 238},
      23: {code: 'base.state_jp_jp-23', name: 'Aichi', id: 201},
      'JP-23': {code: 'base.state_jp_jp-23', name: 'Aichi', id: 201},
      24: {code: 'base.state_jp_jp-24', name: 'Mie', id: 223},
      'JP-24': {code: 'base.state_jp_jp-24', name: 'Mie', id: 223},
      25: {code: 'base.state_jp_jp-25', name: 'Shiga', id: 236},
      'JP-25': {code: 'base.state_jp_jp-25', name: 'Shiga', id: 236},
      26: {code: 'base.state_jp_jp-26', name: 'Kyōto', id: 222},
      'JP-26': {code: 'base.state_jp_jp-26', name: 'Kyōto', id: 222},
      27: {code: 'base.state_jp_jp-27', name: 'Ōsaka', id: 233},
      'JP-27': {code: 'base.state_jp_jp-27', name: 'Ōsaka', id: 233},
      28: {code: 'base.state_jp_jp-28', name: 'Hyōgo', id: 213},
      'JP-28': {code: 'base.state_jp_jp-28', name: 'Hyōgo', id: 213},
      29: {code: 'base.state_jp_jp-29', name: 'Nara', id: 228},
      'JP-29': {code: 'base.state_jp_jp-29', name: 'Nara', id: 228},
      30: {code: 'base.state_jp_jp-30', name: 'Wakayama', id: 244},
      'JP-30': {code: 'base.state_jp_jp-30', name: 'Wakayama', id: 244},
      31: {code: 'base.state_jp_jp-31', name: 'Tottori', id: 241},
      'JP-31': {code: 'base.state_jp_jp-31', name: 'Tottori', id: 241},
      32: {code: 'base.state_jp_jp-32', name: 'Shimane', id: 237},
      'JP-32': {code: 'base.state_jp_jp-32', name: 'Shimane', id: 237},
      33: {code: 'base.state_jp_jp-33', name: 'Okayama', id: 231},
      'JP-33': {code: 'base.state_jp_jp-33', name: 'Okayama', id: 231},
      34: {code: 'base.state_jp_jp-34', name: 'Hiroshima', id: 211},
      'JP-34': {code: 'base.state_jp_jp-34', name: 'Hiroshima', id: 211},
      35: {code: 'base.state_jp_jp-35', name: 'Yamaguchi', id: 246},
      'JP-35': {code: 'base.state_jp_jp-35', name: 'Yamaguchi', id: 246},
      36: {code: 'base.state_jp_jp-36', name: 'Tokushima', id: 240},
      'JP-36': {code: 'base.state_jp_jp-36', name: 'Tokushima', id: 240},
      37: {code: 'base.state_jp_jp-37', name: 'Kagawa', id: 217},
      'JP-37': {code: 'base.state_jp_jp-37', name: 'Kagawa', id: 217},
      38: {code: 'base.state_jp_jp-38', name: 'Ehime', id: 205},
      'JP-38': {code: 'base.state_jp_jp-38', name: 'Ehime', id: 205},
      39: {code: 'base.state_jp_jp-39', name: 'Kōchi', id: 220},
      'JP-39': {code: 'base.state_jp_jp-39', name: 'Kōchi', id: 220},
      40: {code: 'base.state_jp_jp-40', name: 'Fukuoka', id: 207},
      'JP-40': {code: 'base.state_jp_jp-40', name: 'Fukuoka', id: 207},
      41: {code: 'base.state_jp_jp-41', name: 'Saga', id: 234},
      'JP-41': {code: 'base.state_jp_jp-41', name: 'Saga', id: 234},
      42: {code: 'base.state_jp_jp-42', name: 'Nagasaki', id: 227},
      'JP-42': {code: 'base.state_jp_jp-42', name: 'Nagasaki', id: 227},
      43: {code: 'base.state_jp_jp-43', name: 'Kumamoto', id: 221},
      'JP-43': {code: 'base.state_jp_jp-43', name: 'Kumamoto', id: 221},
      44: {code: 'base.state_jp_jp-44', name: 'Ōita', id: 230},
      'JP-44': {code: 'base.state_jp_jp-44', name: 'Ōita', id: 230},
      45: {code: 'base.state_jp_jp-45', name: 'Miyazaki', id: 225},
      'JP-45': {code: 'base.state_jp_jp-45', name: 'Miyazaki', id: 225},
      46: {code: 'base.state_jp_jp-46', name: 'Kagoshima', id: 218},
      'JP-46': {code: 'base.state_jp_jp-46', name: 'Kagoshima', id: 218},
      47: {code: 'base.state_jp_jp-47', name: 'Okinawa', id: 232},
      'JP-47': {code: 'base.state_jp_jp-47', name: 'Okinawa', id: 232},
    },
    name: 'Japan',
    id: 113,
  },
  JE: {code: 'base.je', name: 'Jersey', id: 110},
  JO: {code: 'base.jo', name: 'Jordan', id: 112},
  KZ: {code: 'base.kz', name: 'Kazakhstan', id: 124},
  KE: {code: 'base.ke', name: 'Kenya', id: 114},
  KI: {code: 'base.ki', name: 'Kiribati', id: 117},
  XK: {code: 'base.xk', name: 'Kosovo', id: 250},
  KW: {code: 'base.kw', name: 'Kuwait', id: 122},
  KG: {code: 'base.kg', name: 'Kyrgyzstan', id: 115},
  LA: {code: 'base.la', name: 'Laos', id: 125},
  LV: {code: 'base.lv', name: 'Latvia', id: 134},
  LB: {code: 'base.lb', name: 'Lebanon', id: 126},
  LS: {code: 'base.ls', name: 'Lesotho', id: 131},
  LR: {code: 'base.lr', name: 'Liberia', id: 130},
  LY: {code: 'base.ly', name: 'Libya', id: 135},
  LI: {code: 'base.li', name: 'Liechtenstein', id: 128},
  LT: {code: 'base.lt', name: 'Lithuania', id: 132},
  LU: {code: 'base.lu', name: 'Luxembourg', id: 133},
  MO: {code: 'base.mo', name: 'Macau', id: 147},
  MK: {
    code: 'base.mk',
    name: 'Macedonia, the former Yugoslav Republic of',
    id: 143,
  },
  MG: {code: 'base.mg', name: 'Madagascar', id: 141},
  MW: {code: 'base.mw', name: 'Malawi', id: 155},
  MY: {
    code: 'base.my',
    states: {
      JHR: {code: 'base.state_my_jhr', name: 'Johor', id: 469},
      KDH: {code: 'base.state_my_kdh', name: 'Kedah', id: 470},
      KTN: {code: 'base.state_my_ktn', name: 'Kelantan', id: 471},
      KUL: {code: 'base.state_my_kul', name: 'Kuala Lumpur', id: 472},
      LBN: {code: 'base.state_my_lbn', name: 'Labuan', id: 473},
      MLK: {code: 'base.state_my_mlk', name: 'Melaka', id: 474},
      NSN: {
        code: 'base.state_my_nsn',
        name: 'Negeri Sembilan',
        id: 475,
      },
      PHG: {code: 'base.state_my_phg', name: 'Pahang', id: 476},
      PJY: {code: 'base.state_my_pjy', name: 'Putrajaya', id: 480},
      PLS: {code: 'base.state_my_pls', name: 'Perlis', id: 478},
      PNG: {code: 'base.state_my_png', name: 'Pulau Pinang', id: 479},
      PRK: {code: 'base.state_my_prk', name: 'Perak', id: 477},
      SBH: {code: 'base.state_my_sbh', name: 'Sabah', id: 481},
      SGR: {code: 'base.state_my_sgr', name: 'Selangor', id: 483},
      SWK: {code: 'base.state_my_swk', name: 'Sarawak', id: 482},
      TRG: {code: 'base.state_my_trg', name: 'Terengganu', id: 484},
    },
    name: 'Malaysia',
    id: 157,
  },
  MV: {code: 'base.mv', name: 'Maldives', id: 154},
  ML: {code: 'base.ml', name: 'Mali', id: 144},
  MT: {code: 'base.mt', name: 'Malta', id: 152},
  MH: {code: 'base.mh', name: 'Marshall Islands', id: 142},
  MQ: {code: 'base.mq', name: 'Martinique', id: 149},
  MR: {code: 'base.mr', name: 'Mauritania', id: 150},
  MU: {code: 'base.mu', name: 'Mauritius', id: 153},
  YT: {code: 'base.yt', name: 'Mayotte', id: 246},
  MX: {
    code: 'base.mx',
    states: {
      AG: {
        code: 'base.state_mx_ags',
        name: 'Aguascalientes',
        id: 485,
      },
      AGU: {
        code: 'base.state_mx_ags',
        name: 'Aguascalientes',
        id: 485,
      },
      BC: {
        code: 'base.state_mx_bc',
        name: 'Baja California',
        id: 486,
      },
      BCN: {
        code: 'base.state_mx_bc',
        name: 'Baja California',
        id: 486,
      },
      BS: {
        code: 'base.state_mx_bcs',
        name: 'Baja California Sur',
        id: 487,
      },
      BCS: {
        code: 'base.state_mx_bcs',
        name: 'Baja California Sur',
        id: 487,
      },
      CM: {code: 'base.state_mx_camp', name: 'Campeche', id: 490},
      CAM: {code: 'base.state_mx_camp', name: 'Campeche', id: 490},
      CS: {code: 'base.state_mx_chih', name: 'Chihuahua', id: 488},
      CHH: {code: 'base.state_mx_chih', name: 'Chihuahua', id: 488},
      CH: {code: 'base.state_mx_chis', name: 'Chiapas', id: 492},
      CHP: {code: 'base.state_mx_chis', name: 'Chiapas', id: 492},
      CO: {code: 'base.state_mx_coah', name: 'Coahuila', id: 491},
      COA: {code: 'base.state_mx_coah', name: 'Coahuila', id: 491},
      CL: {code: 'base.state_mx_col', name: 'Colima', id: 489},
      COL: {code: 'base.state_mx_col', name: 'Colima', id: 489},
      DF: {
        code: 'base.state_mx_df',
        name: 'Ciudad de México',
        id: 493,
      },
      DIF: {
        code: 'base.state_mx_df',
        name: 'Ciudad de México',
        id: 493,
      },
      DG: {code: 'base.state_mx_dgo', name: 'Durango', id: 494},
      DUR: {code: 'base.state_mx_dgo', name: 'Durango', id: 494},
      GT: {code: 'base.state_mx_gro', name: 'Guerrero', id: 495},
      GRO: {code: 'base.state_mx_gro', name: 'Guerrero', id: 495},
      GR: {code: 'base.state_mx_gto', name: 'Guanajuato', id: 496},
      GUA: {code: 'base.state_mx_gto', name: 'Guanajuato', id: 496},
      HG: {code: 'base.state_mx_hgo', name: 'Hidalgo', id: 497},
      HID: {code: 'base.state_mx_hgo', name: 'Hidalgo', id: 497},
      JA: {code: 'base.state_mx_jal', name: 'Jalisco', id: 498},
      JAL: {code: 'base.state_mx_jal', name: 'Jalisco', id: 498},
      EM: {code: 'base.state_mx_mex', name: 'México', id: 501},
      MEX: {code: 'base.state_mx_mex', name: 'México', id: 501},
      MI: {code: 'base.state_mx_mich', name: 'Michoacán', id: 499},
      MIC: {code: 'base.state_mx_mich', name: 'Michoacán', id: 499},
      MO: {code: 'base.state_mx_mor', name: 'Morelos', id: 500},
      MOR: {code: 'base.state_mx_mor', name: 'Morelos', id: 500},
      NA: {code: 'base.state_mx_nay', name: 'Nayarit', id: 502},
      NAY: {code: 'base.state_mx_nay', name: 'Nayarit', id: 502},
      NL: {code: 'base.state_mx_nl', name: 'Nuevo León', id: 503},
      NLE: {code: 'base.state_mx_nl', name: 'Nuevo León', id: 503},
      OA: {code: 'base.state_mx_oax', name: 'Oaxaca', id: 504},
      OAX: {code: 'base.state_mx_oax', name: 'Oaxaca', id: 504},
      PU: {code: 'base.state_mx_pue', name: 'Puebla', id: 505},
      PUE: {code: 'base.state_mx_pue', name: 'Puebla', id: 505},
      QT: {code: 'base.state_mx_qro', name: 'Querétaro', id: 507},
      QUE: {code: 'base.state_mx_qro', name: 'Querétaro', id: 507},
      QR: {code: 'base.state_mx_qroo', name: 'Quintana Roo', id: 506},
      ROO: {code: 'base.state_mx_qroo', name: 'Quintana Roo', id: 506},
      SL: {code: 'base.state_mx_sin', name: 'Sinaloa', id: 508},
      SIN: {code: 'base.state_mx_sin', name: 'Sinaloa', id: 508},
      SI: {
        code: 'base.state_mx_slp',
        name: 'San Luis Potosí',
        id: 509,
      },
      SLP: {
        code: 'base.state_mx_slp',
        name: 'San Luis Potosí',
        id: 509,
      },
      SO: {code: 'base.state_mx_son', name: 'Sonora', id: 510},
      SON: {code: 'base.state_mx_son', name: 'Sonora', id: 510},
      TB: {code: 'base.state_mx_tab', name: 'Tabasco', id: 511},
      TAB: {code: 'base.state_mx_tab', name: 'Tabasco', id: 511},
      TM: {code: 'base.state_mx_tamps', name: 'Tamaulipas', id: 513},
      TAM: {code: 'base.state_mx_tamps', name: 'Tamaulipas', id: 513},
      TL: {code: 'base.state_mx_tlax', name: 'Tlaxcala', id: 512},
      TLA: {code: 'base.state_mx_tlax', name: 'Tlaxcala', id: 512},
      VE: {code: 'base.state_mx_ver', name: 'Veracruz', id: 514},
      VER: {code: 'base.state_mx_ver', name: 'Veracruz', id: 514},
      YU: {code: 'base.state_mx_yuc', name: 'Yucatán', id: 515},
      YUC: {code: 'base.state_mx_yuc', name: 'Yucatán', id: 515},
      ZA: {code: 'base.state_mx_zac', name: 'Zacatecas', id: 516},
      ZAC: {code: 'base.state_mx_zac', name: 'Zacatecas', id: 516},
    },
    name: 'Mexico',
    id: 156,
  },
  FM: {code: 'base.fm', name: 'Micronesia', id: 73},
  MD: {code: 'base.md', name: 'Moldova', id: 138},
  MC: {code: 'base.mc', name: 'Monaco', id: 137},
  MN: {
    code: 'base.mn',
    states: {
      1: {code: 'base.state_mn_01', name: 'Архангай', id: 680},
      'MT-1': {code: 'base.state_mn_01', name: 'Архангай', id: 680},
      2: {code: 'base.state_mn_02', name: 'Баян-Өлгий', id: 681},
      'MT-2': {code: 'base.state_mn_02', name: 'Баян-Өлгий', id: 681},
      3: {code: 'base.state_mn_03', name: 'Баянхонгор', id: 682},
      'MT-3': {code: 'base.state_mn_03', name: 'Баянхонгор', id: 682},
      4: {code: 'base.state_mn_04', name: 'Булган', id: 683},
      'MT-4': {code: 'base.state_mn_04', name: 'Булган', id: 683},
      5: {code: 'base.state_mn_05', name: 'Говь-Алтай', id: 684},
      'MT-5': {code: 'base.state_mn_05', name: 'Говь-Алтай', id: 684},
      6: {code: 'base.state_mn_06', name: 'Дорноговь', id: 685},
      'MT-6': {code: 'base.state_mn_06', name: 'Дорноговь', id: 685},
      7: {code: 'base.state_mn_07', name: 'Дорнод', id: 686},
      'MT-7': {code: 'base.state_mn_07', name: 'Дорнод', id: 686},
      8: {code: 'base.state_mn_08', name: 'Дундговь', id: 687},
      'MT-8': {code: 'base.state_mn_08', name: 'Дундговь', id: 687},
      9: {code: 'base.state_mn_09', name: 'Завхан', id: 688},
      'MT-9': {code: 'base.state_mn_09', name: 'Завхан', id: 688},
      10: {code: 'base.state_mn_10', name: 'Өвөрхангай', id: 689},
      'MT-10': {code: 'base.state_mn_10', name: 'Өвөрхангай', id: 689},
      11: {code: 'base.state_mn_11', name: 'Өмнөговь', id: 690},
      'MT-11': {code: 'base.state_mn_11', name: 'Өмнөговь', id: 690},
      12: {code: 'base.state_mn_12', name: 'Сүхбаатар', id: 691},
      'MT-12': {code: 'base.state_mn_12', name: 'Сүхбаатар', id: 691},
      13: {code: 'base.state_mn_13', name: 'Сэлэнгэ', id: 692},
      'MT-13': {code: 'base.state_mn_13', name: 'Сэлэнгэ', id: 692},
      14: {code: 'base.state_mn_14', name: 'Төв', id: 693},
      'MT-14': {code: 'base.state_mn_14', name: 'Төв', id: 693},
      15: {code: 'base.state_mn_15', name: 'Увс', id: 694},
      'MT-15': {code: 'base.state_mn_15', name: 'Увс', id: 694},
      16: {code: 'base.state_mn_16', name: 'Ховд', id: 695},
      'MT-16': {code: 'base.state_mn_16', name: 'Ховд', id: 695},
      17: {code: 'base.state_mn_17', name: 'Хөвсгөл', id: 696},
      'MT-17': {code: 'base.state_mn_17', name: 'Хөвсгөл', id: 696},
      18: {code: 'base.state_mn_18', name: 'Хэнтий', id: 697},
      'MT-18': {code: 'base.state_mn_18', name: 'Хэнтий', id: 697},
      19: {code: 'base.state_mn_19', name: 'Дархан-Уул', id: 698},
      'MT-19': {code: 'base.state_mn_19', name: 'Дархан-Уул', id: 698},
      20: {code: 'base.state_mn_20', name: 'Орхон', id: 699},
      'MT-20': {code: 'base.state_mn_20', name: 'Орхон', id: 699},
      23: {code: 'base.state_mn_23', name: 'УБ - Хан Уул', id: 700},
      'MT-23': {code: 'base.state_mn_23', name: 'УБ - Хан Уул', id: 700},
      24: {code: 'base.state_mn_24', name: 'УБ - Баянзүрх', id: 701},
      'MT-24': {code: 'base.state_mn_24', name: 'УБ - Баянзүрх', id: 701},
      25: {code: 'base.state_mn_25', name: 'УБ - Сүхбаатар', id: 702},
      'MT-25': {code: 'base.state_mn_25', name: 'УБ - Сүхбаатар', id: 702},
      26: {code: 'base.state_mn_26', name: 'УБ - Баянгол', id: 703},
      'MT-26': {code: 'base.state_mn_26', name: 'УБ - Баянгол', id: 703},
      27: {code: 'base.state_mn_27', name: 'УБ - Багануур', id: 704},
      'MT-27': {code: 'base.state_mn_27', name: 'УБ - Багануур', id: 704},
      28: {code: 'base.state_mn_28', name: 'УБ - Багахангай', id: 705},
      'MT-28': {code: 'base.state_mn_28', name: 'УБ - Багахангай', id: 705},
      29: {code: 'base.state_mn_29', name: 'УБ - Налайх', id: 706},
      'MT-29': {code: 'base.state_mn_29', name: 'УБ - Налайх', id: 706},
      32: {code: 'base.state_mn_32', name: 'Говьсүмбэр', id: 707},
      'MT-32': {code: 'base.state_mn_32', name: 'Говьсүмбэр', id: 707},
      34: {
        code: 'base.state_mn_34',
        name: 'УБ - Сонгино Хайрхан',
        id: 708,
      },
      'MT-34': {
        code: 'base.state_mn_34',
        name: 'УБ - Сонгино Хайрхан',
        id: 708,
      },
      35: {code: 'base.state_mn_35', name: 'УБ - Чингэлтэй', id: 709},
      'MT-35': {code: 'base.state_mn_35', name: 'УБ - Чингэлтэй', id: 709},
    },
    name: 'Mongolia',
    id: 146,
  },
  ME: {code: 'base.me', name: 'Montenegro', id: 139},
  MS: {code: 'base.ms', name: 'Montserrat', id: 151},
  MA: {code: 'base.ma', name: 'Morocco', id: 136},
  MZ: {code: 'base.mz', name: 'Mozambique', id: 158},
  MM: {code: 'base.mm', name: 'Myanmar', id: 145},
  NA: {code: 'base.na', name: 'Namibia', id: 159},
  NR: {code: 'base.nr', name: 'Nauru', id: 168},
  NP: {code: 'base.np', name: 'Nepal', id: 167},
  NL: {code: 'base.nl', name: 'Netherlands', id: 165},
  NC: {code: 'base.nc', name: 'New Caledonia', id: 160},
  NZ: {
    code: 'base.nz',
    states: {
      AUK: {code: 'base.state_nz_auk', name: 'Auckland', id: 517},
      BOP: {code: 'base.state_nz_bop', name: 'Bay of Plenty', id: 518},
      CAN: {code: 'base.state_nz_can', name: 'Canterbury', id: 519},
      GIS: {code: 'base.state_nz_gis', name: 'Gisborne', id: 520},
      HKB: {code: 'base.state_nz_hkb', name: "Hawke's Bay", id: 521},
      MBH: {code: 'base.state_nz_mbh', name: 'Marlborough', id: 523},
      MWT: {
        code: 'base.state_nz_mwt',
        name: 'Manawatu-Wanganui',
        id: 522,
      },
      NSN: {code: 'base.state_nz_nsn', name: 'Nelson', id: 524},
      NTL: {code: 'base.state_nz_ntl', name: 'Northland', id: 525},
      OTA: {code: 'base.state_nz_ota', name: 'Otago', id: 526},
      STL: {code: 'base.state_nz_stl', name: 'Southland', id: 527},
      TAS: {code: 'base.state_nz_tas', name: 'Tasman', id: 529},
      TKI: {code: 'base.state_nz_tki', name: 'Taranaki', id: 528},
      WGN: {code: 'base.state_nz_wgn', name: 'Wellington', id: 531},
      WKO: {code: 'base.state_nz_wko', name: 'Waikato', id: 530},
      WTC: {code: 'base.state_nz_wtc', name: 'West Coast', id: 532},
    },
    name: 'New Zealand',
    id: 170,
  },
  NI: {code: 'base.ni', name: 'Nicaragua', id: 164},
  NE: {code: 'base.ne', name: 'Niger', id: 161},
  NG: {code: 'base.ng', name: 'Nigeria', id: 163},
  NU: {code: 'base.nu', name: 'Niue', id: 169},
  NF: {code: 'base.nf', name: 'Norfolk Island', id: 162},
  KP: {code: 'base.kp', name: 'North Korea', id: 120},
  MP: {code: 'base.mp', name: 'Northern Mariana Islands', id: 148},
  NO: {code: 'base.no', name: 'Norway', id: 166},
  OM: {code: 'base.om', name: 'Oman', id: 171},
  PK: {code: 'base.pk', name: 'Pakistan', id: 177},
  PW: {code: 'base.pw', name: 'Palau', id: 184},
  PA: {code: 'base.pa', name: 'Panama', id: 172},
  PG: {code: 'base.pg', name: 'Papua New Guinea', id: 175},
  PY: {code: 'base.py', name: 'Paraguay', id: 185},
  PE: {code: 'base.pe', name: 'Peru', id: 173},
  PH: {code: 'base.ph', name: 'Philippines', id: 176},
  PN: {code: 'base.pn', name: 'Pitcairn Islands', id: 180},
  PL: {code: 'base.pl', name: 'Poland', id: 178},
  PT: {
    code: 'base.pt',
    states: {
      1: {code: 'base.state_pt_pt-01', name: 'Aveiro', id: 248},
      'PT-1': {code: 'base.state_pt_pt-01', name: 'Aveiro', id: 248},
      2: {code: 'base.state_pt_pt-02', name: 'Beja', id: 249},
      'PT-2': {code: 'base.state_pt_pt-02', name: 'Beja', id: 249},
      3: {code: 'base.state_pt_pt-03', name: 'Braga', id: 250},
      'PT-3': {code: 'base.state_pt_pt-03', name: 'Braga', id: 250},
      4: {code: 'base.state_pt_pt-04', name: 'Bragança', id: 251},
      'PT-4': {code: 'base.state_pt_pt-04', name: 'Bragança', id: 251},
      5: {
        code: 'base.state_pt_pt-05',
        name: 'Castelo Branco',
        id: 252,
      },
      'PT-5': {
        code: 'base.state_pt_pt-05',
        name: 'Castelo Branco',
        id: 252,
      },
      6: {code: 'base.state_pt_pt-06', name: 'Coimbra', id: 253},
      'PT-6': {code: 'base.state_pt_pt-06', name: 'Coimbra', id: 253},
      7: {code: 'base.state_pt_pt-07', name: 'Évora', id: 254},
      'PT-7': {code: 'base.state_pt_pt-07', name: 'Évora', id: 254},
      8: {code: 'base.state_pt_pt-08', name: 'Faro', id: 255},
      'PT-8': {code: 'base.state_pt_pt-08', name: 'Faro', id: 255},
      9: {code: 'base.state_pt_pt-09', name: 'Guarda', id: 256},
      'PT-9': {code: 'base.state_pt_pt-09', name: 'Guarda', id: 256},
      10: {code: 'base.state_pt_pt-10', name: 'Leiria', id: 257},
      'PT-10': {code: 'base.state_pt_pt-10', name: 'Leiria', id: 257},
      11: {code: 'base.state_pt_pt-11', name: 'Lisboa', id: 258},
      'PT-11': {code: 'base.state_pt_pt-11', name: 'Lisboa', id: 258},
      12: {code: 'base.state_pt_pt-12', name: 'Portalegre', id: 259},
      'PT-12': {code: 'base.state_pt_pt-12', name: 'Portalegre', id: 259},
      13: {code: 'base.state_pt_pt-13', name: 'Porto', id: 260},
      'PT-13': {code: 'base.state_pt_pt-13', name: 'Porto', id: 260},
      14: {code: 'base.state_pt_pt-14', name: 'Santarém', id: 261},
      'PT-14': {code: 'base.state_pt_pt-14', name: 'Santarém', id: 261},
      15: {code: 'base.state_pt_pt-15', name: 'Setúbal', id: 262},
      'PT-15': {code: 'base.state_pt_pt-15', name: 'Setúbal', id: 262},
      16: {
        code: 'base.state_pt_pt-16',
        name: 'Viana do Castelo',
        id: 263,
      },
      'PT-16': {
        code: 'base.state_pt_pt-16',
        name: 'Viana do Castelo',
        id: 263,
      },
      17: {code: 'base.state_pt_pt-17', name: 'Vila Real', id: 264},
      'PT-17': {code: 'base.state_pt_pt-17', name: 'Vila Real', id: 264},
      18: {code: 'base.state_pt_pt-18', name: 'Viseu', id: 265},
      'PT-18': {code: 'base.state_pt_pt-18', name: 'Viseu', id: 265},
      20: {code: 'base.state_pt_pt-20', name: 'Açores', id: 266},
      'PT-20': {code: 'base.state_pt_pt-20', name: 'Açores', id: 266},
      30: {code: 'base.state_pt_pt-30', name: 'Madeira', id: 267},
      'PT-30': {code: 'base.state_pt_pt-30', name: 'Madeira', id: 267},
    },
    name: 'Portugal',
    id: 183,
  },
  PR: {code: 'base.pr', name: 'Puerto Rico', id: 181},
  QA: {code: 'base.qa', name: 'Qatar', id: 186},
  RO: {code: 'base.ro', name: 'Romania', id: 188},
  RU: {
    code: 'base.ru',
    states: {
      AD: {
        code: 'base.state_ru_ad',
        name: 'Republic of Adygeya',
        id: 98,
      },
      AL: {code: 'base.state_ru_al', name: 'Altai Republic', id: 99},
      ALT: {code: 'base.state_ru_alt', name: 'Altai Krai', id: 100},
      AMU: {code: 'base.state_ru_amu', name: 'Amur Oblast', id: 101},
      ARK: {
        code: 'base.state_ru_ark',
        name: 'Arkhangelsk Oblast',
        id: 102,
      },
      AST: {
        code: 'base.state_ru_ast',
        name: 'Astrakhan Oblast',
        id: 103,
      },
      BA: {
        code: 'base.state_ru_ba',
        name: 'Republic of Bashkortostan',
        id: 104,
      },
      BEL: {
        code: 'base.state_ru_bel',
        name: 'Belgorod Oblast',
        id: 105,
      },
      BRY: {
        code: 'base.state_ru_bry',
        name: 'Bryansk Oblast',
        id: 106,
      },
      BU: {
        code: 'base.state_ru_bu',
        name: 'Republic of Buryatia',
        id: 107,
      },
      CE: {
        code: 'base.state_ru_ce',
        name: 'Chechen Republic',
        id: 108,
      },
      CHE: {
        code: 'base.state_ru_che',
        name: 'Chelyabinsk Oblast',
        id: 109,
      },
      CHU: {
        code: 'base.state_ru_chu',
        name: 'Chukotka Autonomous Okrug',
        id: 110,
      },
      CU: {
        code: 'base.state_ru_cu',
        name: 'Chuvash Republic',
        id: 111,
      },
      DA: {
        code: 'base.state_ru_da',
        name: 'Republic of Dagestan',
        id: 112,
      },
      IN: {
        code: 'base.state_ru_in',
        name: 'Republic of Ingushetia',
        id: 113,
      },
      IRK: {
        code: 'base.state_ru_irk',
        name: 'Irkutsk Oblast',
        id: 114,
      },
      IVA: {
        code: 'base.state_ru_iva',
        name: 'Ivanovo Oblast',
        id: 115,
      },
      KAM: {
        code: 'base.state_ru_kam',
        name: 'Kamchatka Krai',
        id: 116,
      },
      KB: {
        code: 'base.state_ru_kb',
        name: 'Kabardino-Balkarian Republic',
        id: 117,
      },
      KC: {
        code: 'base.state_ru_kc',
        name: 'Karachay–Cherkess Republic',
        id: 121,
      },
      KDA: {
        code: 'base.state_ru_kda',
        name: 'Krasnodar Krai',
        id: 130,
      },
      KEM: {
        code: 'base.state_ru_kem',
        name: 'Kemerovo Oblast',
        id: 123,
      },
      KGD: {
        code: 'base.state_ru_kgd',
        name: 'Kaliningrad Oblast',
        id: 118,
      },
      KGN: {code: 'base.state_ru_kgn', name: 'Kurgan Oblast', id: 132},
      KHA: {
        code: 'base.state_ru_kha',
        name: 'Khabarovsk Krai',
        id: 124,
      },
      KHM: {
        code: 'base.state_ru_khm',
        name: 'Khanty-Mansi Autonomous Okrug',
        id: 126,
      },
      KIR: {code: 'base.state_ru_kir', name: 'Kirov Oblast', id: 127},
      KK: {
        code: 'base.state_ru_kk',
        name: 'Republic of Khakassia',
        id: 125,
      },
      KL: {
        code: 'base.state_ru_kl',
        name: 'Republic of Kalmykia',
        id: 119,
      },
      KLU: {code: 'base.state_ru_klu', name: 'Kaluga Oblast', id: 120},
      KO: {code: 'base.state_ru_ko', name: 'Komi Republic', id: 128},
      KOS: {
        code: 'base.state_ru_kos',
        name: 'Kostroma Oblast',
        id: 129,
      },
      KR: {
        code: 'base.state_ru_kr',
        name: 'Republic of Karelia',
        id: 122,
      },
      KRS: {code: 'base.state_ru_krs', name: 'Kursk Oblast', id: 133},
      KYA: {
        code: 'base.state_ru_kya',
        name: 'Krasnoyarsk Krai',
        id: 131,
      },
      LEN: {
        code: 'base.state_ru_len',
        name: 'Leningrad Oblast',
        id: 134,
      },
      LIP: {
        code: 'base.state_ru_lip',
        name: 'Lipetsk Oblast',
        id: 135,
      },
      MAG: {
        code: 'base.state_ru_mag',
        name: 'Magadan Oblast',
        id: 136,
      },
      ME: {
        code: 'base.state_ru_me',
        name: 'Mari El Republic',
        id: 137,
      },
      MO: {
        code: 'base.state_ru_mo',
        name: 'Republic of Mordovia',
        id: 138,
      },
      MOS: {code: 'base.state_ru_mos', name: 'Moscow Oblast', id: 139},
      MOW: {code: 'base.state_ru_mow', name: 'Moscow', id: 140},
      MUR: {
        code: 'base.state_ru_mur',
        name: 'Murmansk Oblast',
        id: 141,
      },
      NGR: {
        code: 'base.state_ru_ngr',
        name: 'Novgorod Oblast',
        id: 143,
      },
      NIZ: {
        code: 'base.state_ru_niz',
        name: 'Nizhny Novgorod Oblast',
        id: 142,
      },
      NVS: {
        code: 'base.state_ru_nvs',
        name: 'Novosibirsk Oblast',
        id: 144,
      },
      OMS: {code: 'base.state_ru_oms', name: 'Omsk Oblast', id: 145},
      ORE: {
        code: 'base.state_ru_ore',
        name: 'Orenburg Oblast',
        id: 146,
      },
      ORL: {code: 'base.state_ru_orl', name: 'Oryol Oblast', id: 147},
      PER: {code: 'base.state_ru_per', name: 'Perm Krai', id: 149},
      PNZ: {code: 'base.state_ru_pnz', name: 'Penza Oblast', id: 148},
      PRI: {
        code: 'base.state_ru_pri',
        name: 'Primorsky Krai',
        id: 150,
      },
      PSK: {code: 'base.state_ru_psk', name: 'Pskov Oblast', id: 151},
      ROS: {code: 'base.state_ru_ros', name: 'Rostov Oblast', id: 152},
      RYA: {code: 'base.state_ru_rya', name: 'Ryazan Oblast', id: 153},
      SA: {
        code: 'base.state_ru_sa',
        name: 'Sakha Republic (Yakutia)',
        id: 154,
      },
      SAK: {
        code: 'base.state_ru_sak',
        name: 'Sakhalin Oblast',
        id: 155,
      },
      SAM: {code: 'base.state_ru_sam', name: 'Samara Oblast', id: 156},
      SAR: {
        code: 'base.state_ru_sar',
        name: 'Saratov Oblast',
        id: 158,
      },
      SE: {
        code: 'base.state_ru_se',
        name: 'Republic of North Ossetia–Alania',
        id: 159,
      },
      SMO: {
        code: 'base.state_ru_smo',
        name: 'Smolensk Oblast',
        id: 160,
      },
      SPE: {
        code: 'base.state_ru_spe',
        name: 'Saint Petersburg',
        id: 157,
      },
      STA: {
        code: 'base.state_ru_sta',
        name: 'Stavropol Krai',
        id: 161,
      },
      SVE: {
        code: 'base.state_ru_sve',
        name: 'Sverdlovsk Oblast',
        id: 162,
      },
      TA: {
        code: 'base.state_ru_ta',
        name: 'Republic of Tatarstan',
        id: 164,
      },
      TAM: {code: 'base.state_ru_tam', name: 'Tambov Oblast', id: 163},
      TOM: {code: 'base.state_ru_tom', name: 'Tomsk Oblast', id: 165},
      TUL: {code: 'base.state_ru_tul', name: 'Tula Oblast', id: 166},
      TVE: {code: 'base.state_ru_tve', name: 'Tver Oblast', id: 167},
      TY: {code: 'base.state_ru_ty', name: 'Tyva Republic', id: 169},
      TYU: {code: 'base.state_ru_tyu', name: 'Tyumen Oblast', id: 168},
      UD: {code: 'base.state_ru_ud', name: 'Udmurtia', id: 170},
      ULY: {
        code: 'base.state_ru_uly',
        name: 'Ulyanovsk Oblast',
        id: 171,
      },
      VGG: {
        code: 'base.state_ru_vgg',
        name: 'Volgograd Oblast',
        id: 173,
      },
      VLA: {
        code: 'base.state_ru_vla',
        name: 'Vladimir Oblast',
        id: 172,
      },
      VLG: {
        code: 'base.state_ru_vlg',
        name: 'Vologda Oblast',
        id: 174,
      },
      VOR: {
        code: 'base.state_ru_vor',
        name: 'Voronezh Oblast',
        id: 175,
      },
      YAN: {
        code: 'base.state_ru_yan',
        name: 'Yamalo-Nenets Autonomous Okrug',
        id: 176,
      },
      YAR: {
        code: 'base.state_ru_yar',
        name: 'Yaroslavl Oblast',
        id: 177,
      },
      YEV: {
        code: 'base.state_ru_yev',
        name: 'Jewish Autonomous Oblast',
        id: 178,
      },
    },
    name: 'Russian Federation',
    id: 190,
  },
  RW: {code: 'base.rw', name: 'Rwanda', id: 191},
  RE: {code: 'base.re', name: 'Réunion', id: 187},
  BL: {code: 'base.bl', name: 'Saint Barthélémy', id: 26},
  SH: {
    code: 'base.sh',
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    id: 198,
  },
  KN: {code: 'base.kn', name: 'Saint Kitts and Nevis', id: 119},
  LC: {code: 'base.lc', name: 'Saint Lucia', id: 127},
  MF: {code: 'base.mf', name: 'Saint Martin (French part)', id: 140},
  PM: {code: 'base.pm', name: 'Saint Pierre and Miquelon', id: 179},
  VC: {
    code: 'base.vc',
    name: 'Saint Vincent and the Grenadines',
    id: 237,
  },
  WS: {code: 'base.ws', name: 'Samoa', id: 244},
  SM: {code: 'base.sm', name: 'San Marino', id: 203},
  SA: {code: 'base.sa', name: 'Saudi Arabia', id: 192},
  SN: {code: 'base.sn', name: 'Senegal', id: 204},
  RS: {code: 'base.rs', name: 'Serbia', id: 189},
  SC: {code: 'base.sc', name: 'Seychelles', id: 194},
  SL: {code: 'base.sl', name: 'Sierra Leone', id: 202},
  SG: {code: 'base.sg', name: 'Singapore', id: 197},
  SX: {code: 'base.sx', name: 'Sint Maarten (Dutch part)', id: 210},
  SK: {code: 'base.sk', name: 'Slovakia', id: 201},
  SI: {code: 'base.si', name: 'Slovenia', id: 199},
  SB: {code: 'base.sb', name: 'Solomon Islands', id: 193},
  SO: {code: 'base.so', name: 'Somalia', id: 205},
  ZA: {
    code: 'base.za',
    states: {
      EC: {code: 'base.state_za_ec', name: 'Eastern Cape', id: 297},
      FS: {code: 'base.state_za_fs', name: 'Free State', id: 298},
      GT: {code: 'base.state_za_gt', name: 'Gauteng', id: 299},
      LP: {code: 'base.state_za_lp', name: 'Limpopo', id: 301},
      MP: {code: 'base.state_za_mp', name: 'Mpumalanga', id: 302},
      NC: {code: 'base.state_za_nc', name: 'Northern Cape', id: 303},
      NL: {code: 'base.state_za_nl', name: 'KwaZulu-Natal', id: 300},
      NW: {code: 'base.state_za_nw', name: 'North West', id: 304},
      WC: {code: 'base.state_za_wc', name: 'Western Cape', id: 305},
    },
    name: 'South Africa',
    id: 247,
  },
  GS: {
    code: 'base.gs',
    name: 'South Georgia and the South Sandwich Islands',
    id: 89,
  },
  KR: {code: 'base.kr', name: 'South Korea', id: 121},
  SS: {code: 'base.ss', name: 'South Sudan', id: 207},
  ES: {
    code: 'base.es',
    states: {
      A: {
        code: 'base.state_es_a',
        name: 'Alacant (Alicante)',
        id: 420,
      },
      AB: {code: 'base.state_es_ab', name: 'Albacete', id: 419},
      AL: {code: 'base.state_es_al', name: 'Almería', id: 421},
      AV: {code: 'base.state_es_av', name: 'Ávila', id: 423},
      B: {code: 'base.state_es_b', name: 'Barcelona', id: 426},
      BA: {code: 'base.state_es_ba', name: 'Badajoz', id: 424},
      BI: {
        code: 'base.state_es_bi',
        name: 'Bizkaia (Vizcaya)',
        id: 466,
      },
      BU: {code: 'base.state_es_bu', name: 'Burgos', id: 427},
      C: {
        code: 'base.state_es_c',
        name: 'A Coruña (La Coruña)',
        id: 417,
      },
      CA: {code: 'base.state_es_ca', name: 'Cádiz', id: 429},
      CC: {code: 'base.state_es_cc', name: 'Cáceres', id: 428},
      CE: {code: 'base.state_es_ce', name: 'Ceuta', id: 432},
      CO: {code: 'base.state_es_co', name: 'Córdoba', id: 434},
      CR: {code: 'base.state_es_cr', name: 'Ciudad Real', id: 433},
      CS: {
        code: 'base.state_es_cs',
        name: 'Castelló (Castellón)',
        id: 431,
      },
      CU: {code: 'base.state_es_cu', name: 'Cuenca', id: 435},
      GC: {code: 'base.state_es_gc', name: 'Las Palmas', id: 444},
      GI: {code: 'base.state_es_gi', name: 'Girona (Gerona)', id: 436},
      GR: {code: 'base.state_es_gr', name: 'Granada', id: 437},
      GU: {code: 'base.state_es_gu', name: 'Guadalajara', id: 438},
      H: {code: 'base.state_es_h', name: 'Huelva', id: 440},
      HU: {code: 'base.state_es_hu', name: 'Huesca', id: 441},
      J: {code: 'base.state_es_j', name: 'Jaén', id: 442},
      L: {code: 'base.state_es_l', name: 'Lleida (Lérida)', id: 446},
      LE: {code: 'base.state_es_le', name: 'León', id: 445},
      LO: {code: 'base.state_es_lo', name: 'La Rioja', id: 443},
      LU: {code: 'base.state_es_lu', name: 'Lugo', id: 447},
      M: {code: 'base.state_es_m', name: 'Madrid', id: 448},
      MA: {code: 'base.state_es_ma', name: 'Málaga', id: 449},
      ME: {code: 'base.state_es_ml', name: 'Melilla', id: 450},
      MU: {code: 'base.state_es_mu', name: 'Murcia', id: 451},
      NA: {
        code: 'base.state_es_na',
        name: 'Navarra (Nafarroa)',
        id: 452,
      },
      O: {code: 'base.state_es_o', name: 'Asturias', id: 422},
      OR: {
        code: 'base.state_es_or',
        name: 'Ourense (Orense)',
        id: 453,
      },
      P: {code: 'base.state_es_p', name: 'Palencia', id: 454},
      PM: {
        code: 'base.state_es_pm',
        name: 'Illes Balears (Islas Baleares)',
        id: 425,
      },
      PO: {code: 'base.state_es_po', name: 'Pontevedra', id: 455},
      S: {code: 'base.state_es_s', name: 'Cantabria', id: 430},
      SA: {code: 'base.state_es_sa', name: 'Salamanca', id: 456},
      SE: {code: 'base.state_es_se', name: 'Sevilla', id: 459},
      SG: {code: 'base.state_es_sg', name: 'Segovia', id: 458},
      SO: {code: 'base.state_es_so', name: 'Soria', id: 460},
      SS: {
        code: 'base.state_es_ss',
        name: 'Gipuzkoa (Guipúzcoa)',
        id: 439,
      },
      T: {code: 'base.state_es_t', name: 'Tarragona', id: 461},
      TE: {code: 'base.state_es_te', name: 'Teruel', id: 462},
      TF: {
        code: 'base.state_es_tf',
        name: 'Santa Cruz de Tenerife',
        id: 457,
      },
      TO: {code: 'base.state_es_to', name: 'Toledo', id: 463},
      V: {
        code: 'base.state_es_v',
        name: 'València (Valencia)',
        id: 464,
      },
      VA: {code: 'base.state_es_va', name: 'Valladolid', id: 465},
      VI: {code: 'base.state_es_vi', name: 'Araba/Álava', id: 418},
      Z: {code: 'base.state_es_z', name: 'Zaragoza', id: 468},
      ZA: {code: 'base.state_es_za', name: 'Zamora', id: 467},
    },
    name: 'Spain',
    id: 68,
  },
  LK: {code: 'base.lk', name: 'Sri Lanka', id: 129},
  PS: {code: 'base.ps', name: 'State of Palestine', id: 182},
  SD: {code: 'base.sd', name: 'Sudan', id: 195},
  SR: {code: 'base.sr', name: 'Suriname', id: 206},
  SJ: {code: 'base.sj', name: 'Svalbard and Jan Mayen', id: 200},
  SZ: {code: 'base.sz', name: 'Swaziland', id: 212},
  SE: {code: 'base.se', name: 'Sweden', id: 196},
  CH: {code: 'base.ch', name: 'Switzerland', id: 43},
  SY: {code: 'base.sy', name: 'Syria', id: 211},
  ST: {code: 'base.st', name: 'São Tomé and Príncipe', id: 208},
  TW: {code: 'base.tw', name: 'Taiwan', id: 227},
  TJ: {code: 'base.tj', name: 'Tajikistan', id: 218},
  TZ: {code: 'base.tz', name: 'Tanzania', id: 228},
  TH: {code: 'base.th', name: 'Thailand', id: 217},
  TL: {code: 'base.tl', name: 'Timor-Leste', id: 223},
  TG: {code: 'base.tg', name: 'Togo', id: 216},
  TK: {code: 'base.tk', name: 'Tokelau', id: 219},
  TO: {code: 'base.to', name: 'Tonga', id: 222},
  TT: {code: 'base.tt', name: 'Trinidad and Tobago', id: 225},
  TN: {code: 'base.tn', name: 'Tunisia', id: 221},
  TR: {code: 'base.tr', name: 'Turkey', id: 224},
  TM: {code: 'base.tm', name: 'Turkmenistan', id: 220},
  TC: {code: 'base.tc', name: 'Turks and Caicos Islands', id: 213},
  TV: {code: 'base.tv', name: 'Tuvalu', id: 226},
  UM: {code: 'base.um', name: 'USA Minor Outlying Islands', id: 232},
  UG: {code: 'base.ug', name: 'Uganda', id: 230},
  UA: {code: 'base.ua', name: 'Ukraine', id: 229},
  AE: {
    code: 'base.ae',
    states: {
      AJ: {code: 'base.state_ae_aj', name: 'Ajman', id: 547},
      AZ: {code: 'base.state_ae_az', name: 'Abu Dhabi', id: 546},
      DU: {code: 'base.state_ae_du', name: 'Dubai', id: 548},
      FU: {code: 'base.state_ae_fu', name: 'Fujairah', id: 549},
      RK: {code: 'base.state_ae_rk', name: 'Ras al-Khaimah', id: 550},
      SH: {code: 'base.state_ae_sh', name: 'Sharjah', id: 551},
      UQ: {code: 'base.state_ae_uq', name: 'Umm al-Quwain', id: 552},
    },
    name: 'United Arab Emirates',
    id: 2,
  },
  GB: {code: 'base.uk', name: 'United Kingdom', id: 231},
  US: {
    code: 'base.us',
    states: {
      AA: {
        code: 'base.state_us_aa',
        name: 'Armed Forces Americas',
        id: 68,
      },
      AE: {
        code: 'base.state_us_ae',
        name: 'Armed Forces Europe',
        id: 69,
      },
      AK: {code: 'base.state_us_2', name: 'Alaska', id: 10},
      AL: {code: 'base.state_us_1', name: 'Alabama', id: 9},
      AP: {
        code: 'base.state_us_ap',
        name: 'Armed Forces Pacific',
        id: 70,
      },
      AR: {code: 'base.state_us_4', name: 'Arkansas', id: 12},
      AS: {code: 'base.state_us_as', name: 'American Samoa', id: 60},
      AZ: {code: 'base.state_us_3', name: 'Arizona', id: 11},
      CA: {code: 'base.state_us_5', name: 'California', id: 13},
      CO: {code: 'base.state_us_6', name: 'Colorado', id: 14},
      CT: {code: 'base.state_us_7', name: 'Connecticut', id: 15},
      DC: {
        code: 'base.state_us_9',
        name: 'District of Columbia',
        id: 17,
      },
      DE: {code: 'base.state_us_8', name: 'Delaware', id: 16},
      FL: {code: 'base.state_us_10', name: 'Florida', id: 18},
      FM: {
        code: 'base.state_us_fm',
        name: 'Federated States of Micronesia',
        id: 61,
      },
      GA: {code: 'base.state_us_11', name: 'Georgia', id: 19},
      GU: {code: 'base.state_us_gu', name: 'Guam', id: 62},
      HI: {code: 'base.state_us_12', name: 'Hawaii', id: 20},
      IA: {code: 'base.state_us_16', name: 'Iowa', id: 24},
      ID: {code: 'base.state_us_13', name: 'Idaho', id: 21},
      IL: {code: 'base.state_us_14', name: 'Illinois', id: 22},
      IN: {code: 'base.state_us_15', name: 'Indiana', id: 23},
      KS: {code: 'base.state_us_17', name: 'Kansas', id: 25},
      KY: {code: 'base.state_us_18', name: 'Kentucky', id: 26},
      LA: {code: 'base.state_us_19', name: 'Louisiana', id: 27},
      MA: {code: 'base.state_us_34', name: 'Massachusetts', id: 42},
      MD: {code: 'base.state_us_33', name: 'Maryland', id: 41},
      ME: {code: 'base.state_us_20', name: 'Maine', id: 28},
      MH: {code: 'base.state_us_mh', name: 'Marshall Islands', id: 63},
      MI: {code: 'base.state_us_35', name: 'Michigan', id: 43},
      MN: {code: 'base.state_us_36', name: 'Minnesota', id: 44},
      MO: {code: 'base.state_us_38', name: 'Missouri', id: 46},
      MP: {
        code: 'base.state_us_mp',
        name: 'Northern Mariana Islands',
        id: 64,
      },
      MS: {code: 'base.state_us_37', name: 'Mississippi', id: 45},
      MT: {code: 'base.state_us_21', name: 'Montana', id: 29},
      NC: {code: 'base.state_us_28', name: 'North Carolina', id: 36},
      ND: {code: 'base.state_us_29', name: 'North Dakota', id: 37},
      NE: {code: 'base.state_us_22', name: 'Nebraska', id: 30},
      NH: {code: 'base.state_us_24', name: 'New Hampshire', id: 32},
      NJ: {code: 'base.state_us_25', name: 'New Jersey', id: 33},
      NM: {code: 'base.state_us_26', name: 'New Mexico', id: 34},
      NV: {code: 'base.state_us_23', name: 'Nevada', id: 31},
      NY: {code: 'base.state_us_27', name: 'New York', id: 35},
      OH: {code: 'base.state_us_30', name: 'Ohio', id: 38},
      OK: {code: 'base.state_us_31', name: 'Oklahoma', id: 39},
      OR: {code: 'base.state_us_32', name: 'Oregon', id: 40},
      PA: {code: 'base.state_us_39', name: 'Pennsylvania', id: 47},
      PR: {code: 'base.state_us_pr', name: 'Puerto Rico', id: 66},
      PW: {code: 'base.state_us_pw', name: 'Palau', id: 65},
      RI: {code: 'base.state_us_40', name: 'Rhode Island', id: 48},
      SC: {code: 'base.state_us_41', name: 'South Carolina', id: 49},
      SD: {code: 'base.state_us_42', name: 'South Dakota', id: 50},
      TN: {code: 'base.state_us_43', name: 'Tennessee', id: 51},
      TX: {code: 'base.state_us_44', name: 'Texas', id: 52},
      UT: {code: 'base.state_us_45', name: 'Utah', id: 53},
      VA: {code: 'base.state_us_47', name: 'Virginia', id: 55},
      VI: {code: 'base.state_us_vi', name: 'Virgin Islands', id: 67},
      VT: {code: 'base.state_us_46', name: 'Vermont', id: 54},
      WA: {code: 'base.state_us_48', name: 'Washington', id: 56},
      WI: {code: 'base.state_us_50', name: 'Wisconsin', id: 58},
      WV: {code: 'base.state_us_49', name: 'West Virginia', id: 57},
      WY: {code: 'base.state_us_51', name: 'Wyoming', id: 59},
    },
    name: 'United States',
    id: 233,
  },
  UY: {code: 'base.uy', name: 'Uruguay', id: 234},
  UZ: {code: 'base.uz', name: 'Uzbekistan', id: 235},
  VU: {code: 'base.vu', name: 'Vanuatu', id: 242},
  VE: {code: 'base.ve', name: 'Venezuela', id: 238},
  VN: {code: 'base.vn', name: 'Vietnam', id: 241},
  VG: {code: 'base.vg', name: 'Virgin Islands (British)', id: 239},
  VI: {code: 'base.vi', name: 'Virgin Islands (USA)', id: 240},
  WF: {code: 'base.wf', name: 'Wallis and Futuna', id: 243},
  EH: {code: 'base.eh', name: 'Western Sahara', id: 66},
  YE: {code: 'base.ye', name: 'Yemen', id: 245},
  ZM: {code: 'base.zm', name: 'Zambia', id: 248},
  ZW: {code: 'base.zw', name: 'Zimbabwe', id: 249},
  AX: {code: 'base.ax', name: 'Åland Islands', id: 15},
};

/**
 * Get Odoo mapped country code
 * @param {String} countryCode
 */
function getOdooCountry(countryCode) {
  if (!odooLocation[countryCode] || !odooLocation[countryCode].id) {
    return '';
  }
  return odooLocation[countryCode].id;
}

/**
 * See if country has states
 * @param {*} countryCode
 */
function odooCountryHasProvinces(countryCode) {
  if (!odooLocation[countryCode] || !odooLocation[countryCode].id) {
    return false;
  }

  return odooLocation[countryCode].states &&
    Object.keys(odooLocation[countryCode].states).length
    ? true
    : false;
}

/**
 * Get Odoo mapped province code
 * @param {String} countryCode
 * @param {String} provinceCode
 */
function getOdooProvince(countryCode, provinceCode) {
  if (!provinceCode) {
    return '';
  } else if (!odooCountryHasProvinces(countryCode)) {
    return '';
  }

  if (
    !odooLocation[countryCode].states[provinceCode] ||
    !odooLocation[countryCode].states[provinceCode].id
  ) {
    // Try to match by state name instead
    const nameMatch = Object.keys(odooLocation[countryCode].states).reduce(
      (prev, curr) => {
        const state = odooLocation[countryCode].states[curr];
        if (
          !prev &&
          state.name.toLowerCase().indexOf(provinceCode.toLowerCase()) >= 0
        ) {
          return state.id;
        }
        return prev;
      },
      ''
    );

    return nameMatch;
  }

  return odooLocation[countryCode].states[provinceCode].id;
}

module.exports = {
  getOdooCountry,
  odooCountryHasProvinces,
  getOdooProvince,
};
